
name: '🗒️ Repository Request' 
description: 'Request a new repository.'
title: '🗒️ Repository Request: '
body:
- type: checkboxes
  id: operating-systems
  attributes:
    label: Which operating systems have you used?
    description: You may select more than one.
    options:
      - label: macOS
        required: true
      - label: Windows
        required: true
      - label: Linux
        required: true
  
