
name: '🗒️ Repository Request' 
description: 'Request a new repository.'
title: '🗒️ Repository Request: '
body:
  - type: input
    id: name
    attributes:
      label: 'Name'
      description: 'Name of the repository in lower-case and kebab casing.'
      placeholder: 'your-name-kebab'
    validations:
      required: true
  - type: dropdown
    id: department
    attributes:
      label: 'Department'
      description: 'Pick your department. It will be used as a prefix for the repository name.'
      multiple: false
      options:
        - dep1
        - dep2
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
          required: true
        - label: Windows
          required: true
        - label: **Linux**
          required: true
  
